# Generated by Django 4.2.7 on 2023-12-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('trade_date', models.DateField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brokerage', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
